### ISSUE TITLE
Passage de ton répo en privé

### ISSUE THREAD

**Issue by NitriKx** [arnaud33200/M1UPSCours#1]
Si jamais tu veut mettre ton répo en privé, il suffit que t'ajoutes ton adresse UPS dans la liste des adresses email liées à ton compte Github et de suivre les instructions de cette page : https://education.github.com/pack ;-)

**Comment by arnaud33200** [comment]
Merci pour l'info, j'avais envoyé une demande il y a deux mois, ça a pas marché bizarre.
Je laisse le dépot en public, l'année dernière il me servait pour partagé des TP et pour aider les autres mais par expérience, je fais gaffe au gens qui font copier / coller sur les TP notés. Cette année c'est pas important ^^

**Comment by NitriKx** [comment]
En tout cas ça va nous faire économiser un peu de cerveau :-)
